### ISSUE TITLE
implement custom service and characteristic

### ISSUE THREAD

**Issue by DietmarHoch** [Yurik72/ESPHap#24]
Hi, thanks for the great work.

one little question,
is it possible to implement a custom service and characteristic?
i will need it for a smart meter, reading volts, amperes, watts etc.
as I read in the apple spec, I need custom UUIDs for that.

would be great if you could explain that or implement.

Thanks

**Comment by Yurik72** [comment]
Hi, this is question not for this libraty, but to the Apple. Library allows for any usage of services and charachretists available from the Apple (at the moment for the last version), see like [there ](https://developer.apple.com/documentation/homekit/hmservice/accessory_service_types).
This is constraints from the  Apple user interface, what you will be able to see. I know diffrerent implenation from the [Eve](https://www.evehome.com/en/eve-energy), but this is out of the scope currently, Therefore answer is not. However you can implement services like [Ambient light sensor](https://developer.apple.com/forums/thread/36512), to see any values instead of lumens. :)
